import type { MockupViewport } from "./mockup-types.js";

/**
 * Inject a selection probe into stored mockup HTML.
 * The stored source is never mutated — only the served document.
 */
export const MOCKUP_PROBE_FLAG = "data-diffing-probe";

export interface MockupProbeOptions {
  /**
   * Per-document nonce generated by the server. Embedded in the probe and
   * echoed in every posted event so the host UI can tie each event to the
   * exact document (screen + version + viewport) it served.
   */
  nonce?: string;
  /** Layout width the served document is framed at (drives comment scope). */
  viewport?: MockupViewport;
  /**
   * Passive probe: still reports ready/sections and answers anchor checks, but
   * never installs the pointer-capture shield — the mockup stays interactive
   * (buttons/links/forms clickable). Used for the view-only canvas mode.
   */
  passive?: boolean;
}

/**
 * Build the probe script for one served document. The script is parameterized
 * with the document nonce + viewport so every posted event carries them.
 */
export function buildMockupProbeScript(opts: MockupProbeOptions = {}): string {
  const nonce = opts.nonce ?? "";
  const viewport = opts.viewport ?? "desktop";
  const passive = opts.passive === true;
  return `(() => {
  if (window.__diffingMockupProbe) return;
  window.__diffingMockupProbe = true;
  const NONCE = ${JSON.stringify(nonce)};
  const VIEWPORT = ${JSON.stringify(viewport)};
  const PASSIVE = ${passive};
  const BLOCK = 'H1,H2,H3,H4,H5,H6,BUTTON,A,INPUT,TEXTAREA,SELECT,IMG,LI,P,SECTION,ARTICLE,HEADER,TR,TD,LABEL,NAV,ASIDE,FOOTER,FIGURE';
  let tool = 'block';
  let drag = null;
  let shield = null;

  function post(event, extra) {
    try {
      parent.postMessage(Object.assign({ type: 'diffing-mockup', event: event, nonce: NONCE, viewport: VIEWPORT }, extra || {}), '*');
    } catch (_) {}
  }

  function pctRect(el) {
    const r = el.getBoundingClientRect();
    const w = Math.max(document.documentElement.clientWidth, 1);
    const h = Math.max(document.documentElement.clientHeight, 1);
    return {
      x: (r.left / w) * 100,
      y: (r.top / h) * 100,
      w: (r.width / w) * 100,
      h: (r.height / h) * 100,
    };
  }

  function pointPct(ev) {
    const w = Math.max(document.documentElement.clientWidth, 1);
    const h = Math.max(document.documentElement.clientHeight, 1);
    return { x: (ev.clientX / w) * 100, y: (ev.clientY / h) * 100 };
  }

  function cssEscape(s) {
    if (window.CSS && CSS.escape) return CSS.escape(s);
    return String(s).replace(/[^a-zA-Z0-9_-]/g, '\\\\$&');
  }

  function shortSelector(el) {
    if (!el || el === document.documentElement || el === document.body) return 'body';
    const parts = [];
    let node = el;
    for (let i = 0; i < 6 && node && node !== document.body; i++) {
      if (node.getAttribute && node.getAttribute('data-diffing')) {
        parts.unshift('[data-diffing="' + node.getAttribute('data-diffing') + '"]');
        break;
      }
      if (node.id) { parts.unshift('#' + cssEscape(node.id)); break; }
      const tag = node.tagName.toLowerCase();
      const parent = node.parentElement;
      if (!parent) { parts.unshift(tag); break; }
      const cls = (node.className && typeof node.className === 'string')
        ? node.className.trim().split(/\\s+/).filter(Boolean)[0]
        : '';
      const same = Array.from(parent.children).filter((c) => c.tagName === node.tagName);
      const idx = same.indexOf(node) + 1;
      const bit = cls ? tag + '.' + cssEscape(cls) : (same.length > 1 ? tag + ':nth-of-type(' + idx + ')' : tag);
      parts.unshift(bit);
      node = parent;
    }
    return parts.join('>');
  }

  // Stable selector for a block measured from its nearest named section root:
  // '[data-diffing="hero"] > div.row > button.pay:nth-of-type(2)'. Nodes above
  // the section never appear, so edits elsewhere in the document cannot change it.
  function sectionRelativeSelector(el, section) {
    const name = section.getAttribute('data-diffing');
    const root = '[data-diffing="' + name + '"]';
    if (!el || el === section) return root;
    const parts = [];
    let node = el;
    while (node && node !== section) {
      const tag = node.tagName.toLowerCase();
      const parent = node.parentElement;
      let bit = tag;
      if (node.id) {
        bit += '#' + cssEscape(node.id);
      } else {
        const cls = (node.className && typeof node.className === 'string')
          ? node.className.trim().split(/\\s+/).filter(Boolean)[0]
          : '';
        if (cls) bit += '.' + cssEscape(cls);
        if (parent) {
          const same = Array.from(parent.children).filter((c) => c.tagName === node.tagName);
          if (same.length > 1) bit += ':nth-of-type(' + (same.indexOf(node) + 1) + ')';
        }
      }
      parts.unshift(bit);
      node = parent;
    }
    return root + ' > ' + parts.join(' > ');
  }

  // Stable digest of a DOM path. Purely structural — class renames on the
  // block itself change it, but viewport/layout shifts do not.
  function fingerprintOf(path) {
    let h = 5381;
    for (let i = 0; i < path.length; i++) {
      h = ((h << 5) + h + path.charCodeAt(i)) | 0;
    }
    return 'fp:' + (h >>> 0).toString(16);
  }

  function clipHtml(el, max) {
    if (!el || !el.cloneNode) return undefined;
    const clone = el.cloneNode(true);
    if (clone.querySelectorAll) {
      clone.querySelectorAll('script').forEach(function (s) { s.remove(); });
    }
    let html = clone.outerHTML || '';
    if (html.length > max) html = html.slice(0, max) + '\u2026';
    return html;
  }

  function isBlock(el) {
    if (!el || el === document.body || el === document.documentElement) return false;
    if (el.hasAttribute('data-diffing')) return true;
    if (el.id || (el.className && String(el.className).trim())) return true;
    if (el.getAttribute('role')) return true;
    return BLOCK.split(',').includes(el.tagName);
  }

  function deepestBlock(start) {
    let el = start;
    while (el && el !== document.body && !isBlock(el)) el = el.parentElement;
    return el && el !== document.body ? el : start;
  }

  function payloadFor(el, ev, kindOverride) {
    // Nearest named [data-diffing] ancestor only — sections never nest deeper.
    const section = el && el.closest ? el.closest('[data-diffing]') : null;
    const kind = kindOverride || ((tool === 'pin' || tool === 'point') ? 'point' : tool === 'section' && section ? 'section' : 'block');
    const hitEl = deepestBlock(el);
    const outlineEl = kind === 'section' && section ? section : hitEl;
    const pt = ev ? pointPct(ev) : { x: 0, y: 0 };
    let sectionX, sectionY;
    if (section && ev) {
      const sr = section.getBoundingClientRect();
      if (sr.width > 0 && sr.height > 0) {
        sectionX = Math.round(((ev.clientX - sr.left) / sr.width) * 1000) / 10;
        sectionY = Math.round(((ev.clientY - sr.top) / sr.height) * 1000) / 10;
      }
    }
    const base = {
      kind: kind,
      target: section ? section.getAttribute('data-diffing') : undefined,
      x: Math.round(pt.x * 10) / 10,
      y: Math.round(pt.y * 10) / 10,
      sectionX: sectionX,
      sectionY: sectionY,
      rect: outlineEl ? pctRect(outlineEl) : undefined,
    };
    if (kind === 'section' && section) {
      const sel = '[data-diffing="' + section.getAttribute('data-diffing') + '"]';
      return Object.assign(base, {
        selector: sel,
        fingerprint: fingerprintOf(sel),
        html: clipHtml(section, 2000),
        contextHtml: clipHtml(section, 4000),
        snapshot: String(section.innerText || '').trim().slice(0, 240),
      });
    }
    if (kind === 'point') {
      // Pin: coordinate + nearby context. The coordinates are the locator;
      // no deep selector/fingerprint is recorded.
      return Object.assign(base, {
        html: clipHtml(hitEl, 2000),
        contextHtml: clipHtml(section || (hitEl && hitEl.parentElement) || hitEl, 4000),
        snapshot: hitEl ? String(hitEl.innerText || '').trim().slice(0, 240) : undefined,
      });
    }
    // block
    if (section) {
      const sel = sectionRelativeSelector(hitEl, section);
      return Object.assign(base, {
        selector: sel,
        fingerprint: fingerprintOf(sel),
        html: clipHtml(hitEl, 2000),
        contextHtml: clipHtml(section, 4000),
        snapshot: hitEl ? String(hitEl.innerText || '').trim().slice(0, 240) : undefined,
      });
    }
    const sel = hitEl ? shortSelector(hitEl) : undefined;
    return Object.assign(base, {
      selector: sel,
      fingerprint: sel ? fingerprintOf(sel) : undefined,
      html: clipHtml(hitEl, 2000),
      contextHtml: clipHtml(hitEl && hitEl.parentElement, 4000),
      snapshot: hitEl ? String(hitEl.innerText || '').trim().slice(0, 240) : undefined,
    });
  }

  function sections() {
    return Array.from(document.querySelectorAll('[data-diffing]')).map((el) => ({
      name: el.getAttribute('data-diffing'),
      rect: pctRect(el),
    }));
  }

  window.addEventListener('message', (ev) => {
    const d = ev.data;
    if (!d || d.type !== 'diffing-mockup') return;
    if (d.event === 'set-tool' && d.tool) tool = d.tool;
    if (d.event === 'check-anchors' && Array.isArray(d.anchors)) {
      const results = d.anchors.map(function (a) {
        let present = true;
        if (a && a.selector) {
          try { present = !!document.querySelector(a.selector); }
          catch (_) { present = false; }
        }
        return { id: a ? a.id : null, present: present };
      });
      post('anchors', { results: results });
      return;
    }
  });

  function targetAt(ev) {
    if (!shield) return document.body;
    shield.style.pointerEvents = 'none';
    try {
      return document.elementFromPoint(ev.clientX, ev.clientY) || document.body;
    } finally {
      shield.style.pointerEvents = 'auto';
    }
  }

  function installShield() {
    if (shield || !document.body) return;
    const stabilityStyle = document.createElement('style');
    stabilityStyle.setAttribute('data-diffing-stability', '1');
    stabilityStyle.textContent = 'html { scrollbar-gutter: stable; }';
    (document.head || document.documentElement).appendChild(stabilityStyle);

    shield = document.createElement('div');
    shield.setAttribute('data-diffing-inspection-shield', '1');
    shield.setAttribute('aria-hidden', 'true');
    shield.style.cssText = 'position:fixed;inset:0;background:transparent;z-index:2147483647;pointer-events:auto;cursor:crosshair;';
    document.body.appendChild(shield);

    shield.addEventListener('mousemove', (ev) => {
      const target = targetAt(ev);
      if (tool === 'pin' || tool === 'point') {
        post('hover', Object.assign(payloadFor(target, ev, 'point'), { kind: 'point' }));
        return;
      }
      if (tool === 'section') {
        const section = target && target.closest ? target.closest('[data-diffing]') : null;
        if (!section) {
          post('hover-miss');
          return;
        }
        post('hover', payloadFor(section, ev, 'section'));
        return;
      }
      post('hover', payloadFor(target, ev));
    }, true);

    shield.addEventListener('mousedown', (ev) => {
      if (ev.button !== 0) return;
      drag = { x: ev.clientX, y: ev.clientY, target: targetAt(ev) };
      ev.preventDefault();
    }, true);

    shield.addEventListener('mouseup', (ev) => {
      if (ev.button !== 0 || !drag) return;
      const target = targetAt(ev);
      const dx = ev.clientX - drag.x;
      const dy = ev.clientY - drag.y;
      const dist = Math.hypot(dx, dy);
      drag = null;
      if (tool === 'pin' || tool === 'point') {
        post('click', payloadFor(target, ev, 'point'));
        return;
      }
      if (tool === 'section') {
        const section = target && target.closest ? target.closest('[data-diffing]') : null;
        if (!section) {
          post('section-miss');
          return;
        }
        post(dist >= 8 ? 'dragend' : 'click', payloadFor(section, ev, 'section'));
        return;
      }
      post(dist >= 8 ? 'dragend' : 'click', payloadFor(target, ev));
    }, true);

    shield.addEventListener('click', (ev) => {
      ev.preventDefault();
      ev.stopPropagation();
    }, true);
    post('ready', { sections: sections(), height: docHeight() });
  }

  function docHeight() {
    return Math.max(
      document.documentElement.scrollHeight,
      document.body ? document.body.scrollHeight : 0,
    );
  }

  function announce() {
    post('ready', { sections: sections(), height: docHeight() });
  }

  const boot = PASSIVE ? announce : installShield;
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', boot, { once: true });
  } else {
    boot();
  }
  // Keep the parent's frame height in sync after late-loading media and on
  // any reflow (the frame is sized to the full document so nothing is cropped).
  window.addEventListener('load', function () {
    post('height', { height: docHeight() });
  });
  window.addEventListener('resize', function () {
    post('height', { height: docHeight() });
  });
})();`;
}

/** Default probe script (no nonce) — kept for tooling that formats standalone documents. */
export const MOCKUP_PROBE_SCRIPT = buildMockupProbeScript();

export function injectMockupProbe(
  html: string,
  opts: MockupProbeOptions = {},
): string {
  const script = `<script ${MOCKUP_PROBE_FLAG}="1">${buildMockupProbeScript(opts)}</script>`;
  const lower = html.toLowerCase();
  const headIdx = lower.indexOf("<head");
  if (headIdx !== -1) {
    const close = html.indexOf(">", headIdx);
    if (close !== -1) {
      return html.slice(0, close + 1) + script + html.slice(close + 1);
    }
  }
  const htmlIdx = lower.indexOf("<html");
  if (htmlIdx !== -1) {
    const close = html.indexOf(">", htmlIdx);
    if (close !== -1) {
      return html.slice(0, close + 1) + script + html.slice(close + 1);
    }
  }
  return script + html;
}
