// @vitest-environment jsdom
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import { Hono } from "hono";
import { cleanup, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, expect, it, vi } from "vitest";
import { DurableReviewApp } from "../DurableReviewApp";
import { ReviewCore } from "../../../lib/review-core";
import { ReviewAuthority } from "../../../lib/review-authority";
import { ReviewStore } from "../../../lib/review-store";
import { createReviewCoreApi } from "../../../lib/review-core-api";
import { AgentDiffIndexCache } from "../../../lib/agent-diff-index";
import { captureInspection } from "../../../lib/inspect-capture";
import { DEFAULTS } from "../../../lib/diff-options";
import { ReviewClient, prepareReviewRequest } from "../../../lib/review-client";

const close: Array<() => Promise<unknown>> = [];
afterEach(async () => { cleanup(); vi.unstubAllGlobals(); for (const fn of close.splice(0).reverse()) await fn(); });

it("shares capture, comments, viewed state, handoff and human decision with the real core across restart", async () => {
  const directory = await mkdtemp(join(tmpdir(), "durable-browser-flow-"));
  close.push(() => rm(directory, { recursive: true, force: true }));
  const identity = { reviewId: randomUUID(), repositoryId: "a".repeat(64), workspaceId: "b".repeat(64) };
  const authority = new ReviewAuthority();
  const human = authority.issue(identity, { id: "human", kind: "human" }, ["read", "capture", "comment", "handoff", "decide"]);
  const agent = authority.issue(identity, { id: "external-agent", kind: "agent" }, ["read", "capture", "comment", "work"]);
  const patch = "diff --git a/a b/a\n--- a/a\n+++ b/a\n@@ -1 +1 @@\n-old\n+new\n";
  const captured = await captureInspection({ ...DEFAULTS }, async () => ({ patch, complete: true }), async () => ({ repositoryId: identity.repositoryId, workspaceId: identity.workspaceId, head: null, indexDigest: "c".repeat(64), resolvedRevisions: [] }));
  const index = new AgentDiffIndexCache().getOrBuild(patch, true, undefined, captured.manifest);
  const sources = { capture: async () => index, get: (id: string) => id === index.manifest!.snapshotId ? index : undefined };
  const open = () => ReviewCore.open(directory, identity, authority, sources, { openStore: (path) => ReviewStore.open(path) });
  let core = await open(); close.push(() => core.close());
  let app = new Hono().route("/api/review-core", createReviewCoreApi(core));
  const fetcher: typeof fetch = async (input, init) => app.request(String(input), init);
  vi.stubGlobal("fetch", fetcher);
  const agentClient = new ReviewClient({ origin: window.location.origin, identity, credential: agent, fetch: fetcher });
  const connection = () => new File([JSON.stringify({ version: 1, origin: window.location.origin, identity, actor: { id: "human", kind: "human" }, credential: human, headers: { "x-diffing-token": "d".repeat(64) }, expiresAt: Date.now() + 60_000 })], "human.json", { type: "application/json" });
  const user = userEvent.setup();
  render(<DurableReviewApp />);
  await user.upload(screen.getByLabelText("Connection file"), connection());
  await screen.findByText(/Connected as human/);
  await user.click(screen.getByRole("button", { name: "Capture changes" }));
  await screen.findByText("a");
  await user.click(within(screen.getByRole("navigation", { name: "Changed files" })).getByRole("button"));
  await user.click(await screen.findByRole("button", { name: "Comment on new line 1" }));
  await user.type(screen.getByLabelText("Comment on line 1"), "Please verify this line");
  await user.click(screen.getByRole("button", { name: "Comment on line 1" }));
  await screen.findByText("Please verify this line");
  await user.click(screen.getByRole("button", { name: "Mark viewed" }));
  await screen.findByRole("button", { name: "Mark unviewed" });
  await user.type(screen.getByLabelText("Send instructions to agent"), "Check the greeting");
  await user.click(screen.getByRole("button", { name: "Send instructions to agent" }));
  await screen.findByText("Round 1 · available");
  let state = await agentClient.state();
  expect(state.comments).toHaveLength(1);
  expect(state.viewed).toHaveLength(1);
  const handoffId = state.handoffs[0].id;
  await agentClient.execute(prepareReviewRequest(state, { op: "handoff.claim", handoffId }));
  state = await agentClient.state();
  const handoff = state.handoffs[0];
  await agentClient.execute(prepareReviewRequest(state, { op: "handoff.result", handoffId, claimId: handoff.claim!.id, epoch: handoff.epoch, resultSnapshotId: state.currentSnapshotId!, body: "Verified the greeting" }));
  await expect(agentClient.execute(prepareReviewRequest(await agentClient.state(), { op: "decision.record", decision: "approved", rationale: "forged" }))).rejects.toMatchObject({ code: "forbidden", recovery: "request_permission" });
  await user.click(screen.getByRole("button", { name: "Reload review" }));
  await screen.findByText("Verified the greeting");
  await user.type(screen.getByLabelText("Approve round 1"), "Verified against captured source");
  await user.click(screen.getByRole("button", { name: "Approve round 1" }));
  await screen.findByText("Round 1 · reviewed");
  const before = core.state(human);
  expect(before.decisions).toHaveLength(1);
  expect(before.decisions[0]).toMatchObject({ actor: { id: "human", kind: "human" }, handoffId });
  await core.close(); core = await open();
  app = new Hono().route("/api/review-core", createReviewCoreApi(core));
  await user.click(screen.getByRole("button", { name: "Reload review" }));
  await waitFor(() => expect(screen.getByText(`Revision ${before.version}`)).toBeInTheDocument());
  expect(core.state(human)).toEqual(before);
  expect(within(screen.getByRole("complementary", { name: "Review discussion" })).getByText("Verified against captured source")).toBeInTheDocument();
}, 15_000);
